name: publish package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: macos-12
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        needs: build-job
        with:
          name: output-tar

      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      # - run: npm install

      - run: tar -zxvf output.tar.gz && cd output && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
